# Generated by Django 5.2.7 on 2026-01-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
