# Generated by Django 5.2.7 on 2026-01-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='City_town',
            new_name='city_town',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Date_of_birth',
            new_name='date_of_birth',
        ),
    ]
