# Generated by Django 5.2.7 on 2026-01-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0002_module_remove_issue_description_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.AddField(
            model_name='module',
            name='course',
            field=models.ManyToManyField(related_name='module', to='itreporting.course'),
        ),
    ]
