# Generated by Django 5.2.7 on 2026-01-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0004_remove_module_course_module_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.AddField(
            model_name='module',
            name='courses',
            field=models.ManyToManyField(related_name='modules', to='itreporting.course'),
        ),
    ]
